source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HDDemoSpec_Example', :exclusive => true do
  pod "HDDemoSpec", :path => "../"
end

target 'HDDemoSpec_Tests', :exclusive => true do
  pod "HDDemoSpec", :path => "../"

  
end
